### ISSUE TITLE
IAAPerspective corrupts the mask

### ISSUE THREAD

**Issue by geohot** [YassineYousfi/comma10k-baseline#2]
https://albumentations.ai/docs/api_reference/imgaug/transforms/#albumentations.imgaug.transforms.IAAPerspective

"Note: This class introduce interpolation artifacts to mask if it has values other than {0;1}"

**Comment by YassineYousfi** [comment]
Thanks for pointing this out! The mask is one-hot encoded in this version (line 81 in retriever.py) 

But I will definitely keep an eye on this warning for future versions!

**Comment by YassineYousfi** [comment]
Ok it still corrupts because the mask is a float, using uint8 fixes it.

**Comment by YassineYousfi** [comment]
The corruption in terms of argmax is minimal (around 0.1% of pixels affected) so there is no need to retrain the net. Thanks @geohot

**Comment by geohot** [comment]
Does uint8 fix it? I couldn't make it work.

I agree it's minimal, but it's annoying and the model will waste capacity on it, all the uncertainty is at the edges.

**Comment by YassineYousfi** [comment]
one-hot encoding + uint8 didn't corrupt any pixel in my case. How do you test for corruption?

**Comment by YassineYousfi** [comment]
I see what could go wrong with this fix, since the masks are treated independently, some mask pixels might collide, as you said this happens at the boundaries. 

e.g. the little yellow pixels in this screenshot. Is this what you experienced?

![image](https://user-images.githubusercontent.com/29985433/101567577-0e740580-399f-11eb-88d0-0afc52ab450a.png)

**Comment by geohot** [comment]
Yea, it interpolates at the boundaries.

**Comment by YassineYousfi** [comment]
Right,
I think there has been a major update between the imgaug (used by A.) version this repo uses (0.2.5) and the last stable (0.4.0) which deals a little better with segmentation masks.
I'm still not sure why they don't use cv2.INTER_NEAREST to deal with these issues... IAAPerspective is just a cv2.warpPerspective I suppose.
Anyways, I'm currently researching different augmentation pipelines, so I'll probably avoid IAAPerspective in the next versions, or write my own if it appears to be beneficial.

**Comment by YassineYousfi** [comment]
I get an even better CCE with a new augmentation pipeline without IAAPerspective and adding a few more 🔥 (0.0441) releasing it tonight.
