### ISSUE TITLE
No pretict masks output

### ISSUE THREAD

**Issue by lmz0528** [YassineYousfi/comma10k-baseline#6]
![error](https://user-images.githubusercontent.com/75722073/147446304-80ec7b35-e169-4a5b-9cf3-bd2a272391ea.jpg)
Hi,i am trying to predict imgs with using predict_folder.py
It doesn't look wrong but after command,there is still nothing in the folder {predicted_masks}
Could you help me solve it?
Any comments are greatly appreciated
Thank you

**Comment by lmz0528** [comment]
I solved it,wrong environment.
Thank you

**Comment by YassineYousfi** [comment]
Glad you solved it.
